CREATE TABLE APP_CONFIG (ID INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            VERSION_CODE TEXT NOT NULL,
            VERSION_NAME TEXT NOT NULL,
            COMMENTS TEXT);

-- INSERTS
INSERT INTO APP_CONFIG(CREATE_DATE, VERSION_CODE, VERSION_NAME, COMMENTS) VALUES ("04/04/2016","1", "1.0.0", "Version inicial");
INSERT INTO APP_CONFIG(CREATE_DATE, VERSION_CODE, VERSION_NAME, COMMENTS) VALUES ("04/05/2016","2", "1.0.1", "Corrección visualización de mapas. Error de licencia.");