CREATE TABLE FORM_DESIGN (ID_FORM_DESIGN INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            AUTHOR TEXT NOT NULL,
            FORM_NAME TEXT NOT NULL,
            FORM_DESCRIPTION TEXT NOT NULL, 
            FORM_TRACKEABLE BOOLEAN NOT NULL);
			
CREATE TABLE QUESTION_DESIGN (ID_QUESTION_DESIGN INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            AUTHOR TEXT NOT NULL,
            ID_FORM_DESIGN INTEGER NOT NULL,
            ID_QUESTION_TYPE INTEGER NOT NULL,
            QUESTION TEXT NOT NULL,
            MANDATORY_ASNWER BOOLEAN NOT NULL DEFAULT FALSE);			

CREATE TABLE ANSWER_DESIGN (ID_ANSWER_DESIGN INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            AUTHOR TEXT NOT NULL,
            ID_QUESTION_DESIGN INTEGER NOT NULL,
            ID_ANSWER_TYPE INTEGER NOT NULL,
            ANSWER TEXT NOT NULL);
			
CREATE TABLE QUESTION_TYPE (ID_QUESTION_TYPE INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            QUESTION_TYPE TEXT NOT NULL);
			
CREATE TABLE ANSWER_TYPE (ID_ANSWER_TYPE INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            ANSWER_TYPE TEXT NOT NULL);

-- TABLAS DE FORMULARIOS CUMPLIMENTADOS POR USUARIOS
CREATE TABLE USER_FORMS (ID_USER_FORM INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            ID_FORM INTEGER NOT NULL,
            USER_NAME TEXT NOT NULL,
            DESCRIPTION TEXT NOT NULL);
			
CREATE TABLE USER_ANSWERS (ID_USER_ANSWER INTEGER PRIMARY KEY AUTO_INCREMENT,
            CREATE_DATE DATE,
            AUTHOR TEXT NOT NULL,
            ID_USER_FORM INTEGER NOT NULL,
            ID_USER_QUESTION INTEGER NOT NULL,
            USER_ANSWER_ID INTEGER,
            USER_ANSWER_TEXT TEXT,
            LATITUDE TEXT,
            LONGITUDE TEXT,
            ADDRESS TEXT);
			
CREATE TABLE USER_MULTIPLE_ANSWERS (ID_USER_MULTIPLE_ANSWERS INTEGER PRIMARY KEY AUTOINCREMENT,
            CREATE_DATE DATE,
            AUTHOR TEXT NOT NULL,
            ID_USER_ANSWER INTEGER NOT NULL,
            ANSWER_ID INTEGER NOT NULL,
            MULTIPLE_ANSWER_TEXT TEXT NOT NULL);
			
			
-- INSERTS
INSERT INTO QUESTION_TYPE(CREATE_DATE, QUESTION_TYPE) VALUES ("22/04/2016","Respuesta única");
INSERT INTO QUESTION_TYPE(CREATE_DATE, QUESTION_TYPE) VALUES ("22/04/2016","Respuesta múltiple");
INSERT INTO QUESTION_TYPE(CREATE_DATE, QUESTION_TYPE) VALUES ("22/04/2016","Realizar fotografía");
INSERT INTO QUESTION_TYPE(CREATE_DATE, QUESTION_TYPE) VALUES ("22/04/2016","Seleccionar ubicación");
INSERT INTO QUESTION_TYPE(CREATE_DATE, QUESTION_TYPE) VALUES ("22/04/2016","Texto libre");
INSERT INTO QUESTION_TYPE(CREATE_DATE, QUESTION_TYPE) VALUES ("22/04/2016","Código de barras");